development:
  adapter: postgresql
  encoding: unicode
  database: tdlist_development
  pool: 5
  username: den
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: tdlist_test
  pool: 5
  username: den
  password: 

production:
  adapter: postgresql
  encoding: unicode
  database: tdlist_production
  pool: 5
  host: localhost
  username: den
  password: 